/**
 * Booking.com hotel integration for TripAmigos
 *
 * MVP approach: mock data structured to match the Booking.com Demand API v3 response format.
 * When you get affiliate credentials, swap searchHotels() internals to hit the real API.
 *
 * Real API docs: https://developers.booking.com/demand/docs/open-api/demand-api
 * Sign up: https://partnerships.booking.com/
 */

export const BOOKING_AFFILIATE_ID = process.env.BOOKING_AFFILIATE_ID || ''

// =====================================================
// TYPES (mirrors Demand API response shape)
// =====================================================

export interface HotelOption {
  id: string
  name: string
  starRating: number
  reviewScore: number
  reviewCount: number
  reviewWord: string
  address: string
  city: string
  country: string
  photoUrl: string
  amenities: string[]
  distanceFromCentre: string
  pricePerNight: number
  totalPrice: number
  currency: string
  nights: number
  guests: number
  rooms: number
  roomType: string
  freeCancellation: boolean
  breakfastIncluded: boolean
  bookingUrl: string
  tier: 'budget' | 'mid-range' | 'premium'
  tierLabel: string
  description: string
  highlights: string[]
  reviewBreakdown: { category: string; score: number }[]
  checkInTime: string
  checkOutTime: string
  neighbourhood: string
}

// =====================================================
// HOTEL DATABASE — realistic mock data per destination
// =====================================================

interface HotelTemplate {
  name: string
  starRating: number
  reviewScore: number
  reviewCount: number
  reviewWord: string
  amenities: string[]
  distanceFromCentre: string
  roomType: string
  freeCancellation: boolean
  breakfastIncluded: boolean
  tier: 'budget' | 'mid-range' | 'premium'
  basePricePerNight: number // per room
  photoSlug: string
  description: string
  highlights: string[]
  reviewBreakdown: { category: string; score: number }[]
  checkInTime: string
  checkOutTime: string
  neighbourhood: string
}

// Hotels for major destinations — 3 tiers per city
const HOTEL_DATA: Record<string, { country: string; hotels: HotelTemplate[] }> = {
  'Barcelona': {
    country: 'Spain',
    hotels: [
      {
        name: 'Generator Barcelona',
        starRating: 3,
        reviewScore: 8.1,
        reviewCount: 4230,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Bar', 'Terrace', 'Shared kitchen', '24h reception'],
        distanceFromCentre: '0.8 km from centre',
        roomType: 'Private room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 32,
        photoSlug: 'generator-bcn',
        description: 'A vibrant social hostel located in the heart of Barcelona, perfect for backpackers and solo travelers. Featuring a lively bar and terrace scene, it offers excellent value with easy access to Gothic Quarter attractions.',
        highlights: ['Social bar with terrace views', 'Shared kitchen facility', 'Prime location near Gothic Quarter'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.2 },
          { category: 'Facilities', score: 7.9 },
          { category: 'Cleanliness', score: 8.0 },
          { category: 'Comfort', score: 7.8 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.3 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Gothic Quarter, Barcelona',
      },
      {
        name: 'Hotel Jazz Barcelona',
        starRating: 4,
        reviewScore: 8.6,
        reviewCount: 3180,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Rooftop pool', 'Gym', 'Bar', 'Air conditioning', 'City views'],
        distanceFromCentre: '0.3 km from centre',
        roomType: 'Superior twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 145,
        photoSlug: 'jazz-bcn',
        description: 'A stylish boutique hotel in Barcelona\'s historic center offering rooftop views and modern amenities. Located steps from La Rambla, it combines contemporary design with traditional Catalan charm.',
        highlights: ['Rooftop pool with city views', '5-minute walk to La Rambla', 'Included breakfast buffet'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.8 },
          { category: 'Facilities', score: 8.5 },
          { category: 'Cleanliness', score: 8.7 },
          { category: 'Comfort', score: 8.4 },
          { category: 'Value', score: 8.3 },
          { category: 'Location', score: 8.9 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'City Centre, Barcelona',
      },
      {
        name: 'Hotel Arts Barcelona',
        starRating: 5,
        reviewScore: 9.2,
        reviewCount: 2740,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Infinity pool', 'Fine dining', 'Beach access', 'Concierge', 'Gym'],
        distanceFromCentre: '1.2 km from centre',
        roomType: 'Deluxe sea view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 380,
        photoSlug: 'arts-bcn',
        description: 'A flagship luxury hotel with iconic architecture and world-class service on Barcelona\'s waterfront. Features an infinity pool, Michelin-starred dining, and direct beach access with panoramic Mediterranean views.',
        highlights: ['Infinity pool with sea views', 'Direct private beach access', 'Michelin-starred fine dining'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.4 },
          { category: 'Facilities', score: 9.3 },
          { category: 'Cleanliness', score: 9.2 },
          { category: 'Comfort', score: 9.1 },
          { category: 'Value', score: 8.9 },
          { category: 'Location', score: 9.3 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Port Vell, Barcelona',
      },
    ],
  },
  'Amsterdam': {
    country: 'Netherlands',
    hotels: [
      {
        name: 'ClinkNOORD Amsterdam',
        starRating: 3,
        reviewScore: 8.0,
        reviewCount: 5120,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Bar', 'Games room', 'Café', '24h reception'],
        distanceFromCentre: '1.5 km from centre',
        roomType: 'Private 4-bed room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 38,
        photoSlug: 'clink-ams',
        description: 'A buzzing budget hostel popular with travelers in Amsterdam\'s vibrant Noord district. Features a lively bar and games room, offering excellent value and authentic local culture across the river.',
        highlights: ['Lively games room and bar', 'Ferry access to city center', 'Great budget value'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.1 },
          { category: 'Facilities', score: 7.8 },
          { category: 'Cleanliness', score: 8.0 },
          { category: 'Comfort', score: 7.9 },
          { category: 'Value', score: 8.3 },
          { category: 'Location', score: 7.9 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Noord, Amsterdam',
      },
      {
        name: 'DoubleTree by Hilton Amsterdam Centraal',
        starRating: 4,
        reviewScore: 8.4,
        reviewCount: 2890,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Gym', 'Restaurant', 'Bar', 'Air conditioning', 'Canal views'],
        distanceFromCentre: '0.2 km from centre',
        roomType: 'Twin guest room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 185,
        photoSlug: 'doubletree-ams',
        description: 'A modern 4-star hotel perfectly positioned next to Amsterdam\'s Central Station with stunning canal views. Offers comfortable rooms, a restaurant, and direct access to train connections and the city\'s attractions.',
        highlights: ['Adjacent to Central Station', 'Beautiful canal views', 'Full breakfast included'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.5 },
          { category: 'Facilities', score: 8.3 },
          { category: 'Cleanliness', score: 8.4 },
          { category: 'Comfort', score: 8.5 },
          { category: 'Value', score: 8.2 },
          { category: 'Location', score: 8.6 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'City Centre, Amsterdam',
      },
      {
        name: 'Waldorf Astoria Amsterdam',
        starRating: 5,
        reviewScore: 9.4,
        reviewCount: 1480,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Pool', 'Michelin restaurant', 'Canal-side', 'Butler service', 'Gym'],
        distanceFromCentre: '0.4 km from centre',
        roomType: 'King canal view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 520,
        photoSlug: 'waldorf-ams',
        description: 'Amsterdam\'s most prestigious luxury hotel set in a historic palace on the city\'s finest canal. Features Michelin-starred dining, exclusive spa, butler service, and unparalleled elegance for the most discerning travelers.',
        highlights: ['Michelin-starred restaurant', 'Full-service spa with pool', 'Personal butler service included'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.6 },
          { category: 'Facilities', score: 9.5 },
          { category: 'Cleanliness', score: 9.4 },
          { category: 'Comfort', score: 9.3 },
          { category: 'Value', score: 9.1 },
          { category: 'Location', score: 9.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Grachtengordel, Amsterdam',
      },
    ],
  },
  'Paris': {
    country: 'France',
    hotels: [
      {
        name: 'Generator Paris',
        starRating: 3,
        reviewScore: 7.8,
        reviewCount: 6340,
        reviewWord: 'Good',
        amenities: ['Wi-Fi', 'Bar', 'Terrace', 'Café', '24h reception'],
        distanceFromCentre: '2.5 km from centre',
        roomType: 'Private quad room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 35,
        photoSlug: 'generator-paris',
        description: 'A sociable hostel in eastern Paris popular with budget travelers and backpackers. Offers a vibrant bar atmosphere, terrace, and a great base for exploring the Marais and Canal Saint-Martin neighborhoods.',
        highlights: ['Lively rooftop terrace', 'Social bar scene', 'Close to Canal Saint-Martin'],
        reviewBreakdown: [
          { category: 'Staff', score: 7.9 },
          { category: 'Facilities', score: 7.7 },
          { category: 'Cleanliness', score: 7.8 },
          { category: 'Comfort', score: 7.6 },
          { category: 'Value', score: 8.1 },
          { category: 'Location', score: 7.8 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Belleville, Paris',
      },
      {
        name: 'Hôtel Le Compostelle',
        starRating: 4,
        reviewScore: 8.7,
        reviewCount: 2150,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Bar', 'Air conditioning', 'Concierge', 'Near Champs-Élysées'],
        distanceFromCentre: '0.5 km from centre',
        roomType: 'Classic twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 195,
        photoSlug: 'compostelle-paris',
        description: 'A charming 4-star hotel on the prestigious Avenue des Champs-Élysées near the Arc de Triomphe. Blends Parisian elegance with modern comfort, offering a concierge service and gourmet breakfast.',
        highlights: ['Steps from Champs-Élysées', 'Arc de Triomphe nearby', 'Gourmet breakfast included'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.8 },
          { category: 'Facilities', score: 8.6 },
          { category: 'Cleanliness', score: 8.8 },
          { category: 'Comfort', score: 8.7 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.9 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Champs-Élysées, Paris',
      },
      {
        name: 'Le Meurice – Dorchester Collection',
        starRating: 5,
        reviewScore: 9.5,
        reviewCount: 980,
        reviewWord: 'Exceptional',
        amenities: ['Wi-Fi', 'Spa', 'Michelin restaurant', 'Tuileries views', 'Butler', 'Gym', 'Concierge'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Deluxe room with garden view',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 680,
        photoSlug: 'meurice-paris',
        description: 'Paris\'s legendary luxury palace hotel facing the Tuileries Gardens with impeccable service since 1835. Boasts a Michelin-starred restaurant, world-class spa, and rooms overlooking the Seine and royal gardens.',
        highlights: ['Michelin-starred fine dining', 'Overlooking Tuileries Gardens', 'Luxury spa and butler service'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.7 },
          { category: 'Facilities', score: 9.6 },
          { category: 'Cleanliness', score: 9.5 },
          { category: 'Comfort', score: 9.5 },
          { category: 'Value', score: 9.2 },
          { category: 'Location', score: 9.6 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Tuileries, Paris',
      },
    ],
  },
  'Rome': {
    country: 'Italy',
    hotels: [
      {
        name: 'The Yellow Hostel',
        starRating: 3,
        reviewScore: 8.2,
        reviewCount: 3780,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Bar', 'Terrace', 'Air conditioning', 'Near Termini'],
        distanceFromCentre: '1.0 km from centre',
        roomType: 'Private room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 28,
        photoSlug: 'yellow-rome',
        description: 'A fun and lively budget hostel near Rome\'s Termini Station with a popular bar and terrace. Perfect for backpackers seeking affordable accommodation and a social atmosphere with easy access to ancient ruins.',
        highlights: ['Social bar and rooftop terrace', 'Steps from Termini Station', 'Walking distance to Colosseum'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.3 },
          { category: 'Facilities', score: 8.0 },
          { category: 'Cleanliness', score: 8.1 },
          { category: 'Comfort', score: 8.0 },
          { category: 'Value', score: 8.4 },
          { category: 'Location', score: 8.4 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Esquilino, Rome',
      },
      {
        name: 'Hotel Artemide',
        starRating: 4,
        reviewScore: 9.0,
        reviewCount: 4560,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Rooftop bar', 'Restaurant', 'Air conditioning', 'Gym'],
        distanceFromCentre: '0.3 km from centre',
        roomType: 'Superior twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 165,
        photoSlug: 'artemide-rome',
        description: 'An elegant 4-star hotel in Rome\'s historic center near the Pantheon with a renowned rooftop bar overlooking the city. Offers spa facilities, fine dining, and comfortable rooms combining modern amenities with Roman charm.',
        highlights: ['Panoramic rooftop bar views', 'Walking distance to Pantheon', 'Spa and gourmet restaurant'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.1 },
          { category: 'Facilities', score: 8.9 },
          { category: 'Cleanliness', score: 9.0 },
          { category: 'Comfort', score: 8.9 },
          { category: 'Value', score: 8.8 },
          { category: 'Location', score: 9.2 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Pantheon District, Rome',
      },
      {
        name: 'Hotel de Russie – Rocco Forte',
        starRating: 5,
        reviewScore: 9.3,
        reviewCount: 1250,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Secret garden', 'Fine dining', 'Gym', 'Concierge', 'Piazza del Popolo'],
        distanceFromCentre: '0.2 km from centre',
        roomType: 'Deluxe garden room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 490,
        photoSlug: 'russie-rome',
        description: 'Rome\'s most prestigious hotel overlooking Piazza del Popolo featuring a hidden secret garden and exclusive luxury. Offers world-class fine dining, full-service spa, and rooms with stunning views of Rome\'s most charming piazza.',
        highlights: ['Private secret garden sanctuary', 'Overlooks Piazza del Popolo', 'Michelin-starred dining'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.5 },
          { category: 'Facilities', score: 9.3 },
          { category: 'Cleanliness', score: 9.4 },
          { category: 'Comfort', score: 9.2 },
          { category: 'Value', score: 9.0 },
          { category: 'Location', score: 9.4 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Piazza del Popolo, Rome',
      },
    ],
  },
  'Lisbon': {
    country: 'Portugal',
    hotels: [
      {
        name: 'Lisbon Destination Hostel',
        starRating: 3,
        reviewScore: 8.5,
        reviewCount: 2890,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Bar', 'Common area', 'Walking tours', '24h reception'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Private quad room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 25,
        photoSlug: 'destination-lisbon',
        description: 'An excellent budget hostel in the heart of Lisbon\'s Baixa district with knowledgeable staff and organized walking tours. Great for meeting travelers and exploring the city\'s historic center on a shoestring budget.',
        highlights: ['Free walking tours daily', 'Located in historic Baixa', 'Social bar atmosphere'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.6 },
          { category: 'Facilities', score: 8.4 },
          { category: 'Cleanliness', score: 8.5 },
          { category: 'Comfort', score: 8.3 },
          { category: 'Value', score: 8.7 },
          { category: 'Location', score: 8.7 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Baixa, Lisbon',
      },
      {
        name: 'Hotel do Chiado',
        starRating: 4,
        reviewScore: 8.8,
        reviewCount: 1920,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Rooftop terrace', 'Bar', 'Air conditioning', 'City views', 'Restaurant'],
        distanceFromCentre: '0.3 km from centre',
        roomType: 'Classic twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 135,
        photoSlug: 'chiado-lisbon',
        description: 'A contemporary 4-star boutique hotel in the charming Chiado district with literary heritage and vibrant cultural scene. Features a rooftop terrace with city views, restaurant, and stylish rooms in a historic neighborhood.',
        highlights: ['Rooftop terrace with city views', 'Historic Chiado district location', 'Gourmet restaurant on-site'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.9 },
          { category: 'Facilities', score: 8.7 },
          { category: 'Cleanliness', score: 8.8 },
          { category: 'Comfort', score: 8.8 },
          { category: 'Value', score: 8.6 },
          { category: 'Location', score: 8.9 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Chiado, Lisbon',
      },
      {
        name: 'Four Seasons Hotel Ritz Lisbon',
        starRating: 5,
        reviewScore: 9.1,
        reviewCount: 1640,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Pool', 'Fine dining', 'Park views', 'Gym', 'Concierge'],
        distanceFromCentre: '1.5 km from centre',
        roomType: 'Deluxe park view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 420,
        photoSlug: 'ritz-lisbon',
        description: 'Lisbon\'s premier luxury hotel overlooking the stunning Edward VII Park with impeccable service and elegant design. Boasts a Michelin-starred restaurant, world-class spa, and rooms with panoramic city and river views.',
        highlights: ['Overlooks Edward VII Park', 'Michelin-starred fine dining', 'Full-service spa with pool'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.3 },
          { category: 'Facilities', score: 9.1 },
          { category: 'Cleanliness', score: 9.2 },
          { category: 'Comfort', score: 9.0 },
          { category: 'Value', score: 8.8 },
          { category: 'Location', score: 9.1 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Marquês de Pombal, Lisbon',
      },
    ],
  },
  'Prague': {
    country: 'Czech Republic',
    hotels: [
      {
        name: 'Mosaic House Prague',
        starRating: 3,
        reviewScore: 8.3,
        reviewCount: 3420,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Bar', 'Music lounge', 'Eco-friendly', '24h reception'],
        distanceFromCentre: '0.8 km from centre',
        roomType: 'Private room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 22,
        photoSlug: 'mosaic-prague',
        description: 'An eco-conscious hostel with a fun atmosphere featuring a lively bar and music lounge. Located near Vinohrady, it\'s a great budget choice with modern facilities and easy access to Prague\'s historic center.',
        highlights: ['Music lounge and bar', 'Eco-friendly building', 'Walking distance to Old Town'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.4 },
          { category: 'Facilities', score: 8.2 },
          { category: 'Cleanliness', score: 8.3 },
          { category: 'Comfort', score: 8.1 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.3 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Vinohrady, Prague',
      },
      {
        name: 'Moods Charles Bridge',
        starRating: 4,
        reviewScore: 8.9,
        reviewCount: 1870,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Bar', 'Air conditioning', 'Near Charles Bridge', 'Concierge'],
        distanceFromCentre: '0.2 km from centre',
        roomType: 'Superior twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 110,
        photoSlug: 'moods-prague',
        description: 'A charming 4-star hotel steps from the iconic Charles Bridge in Prague\'s Old Town. Features stylish rooms, a popular bar, and prime views of Prague\'s Medieval architecture and the Vltava River.',
        highlights: ['Adjacent to Charles Bridge', 'Old Town Square nearby', 'Views of Vltava River'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.0 },
          { category: 'Facilities', score: 8.8 },
          { category: 'Cleanliness', score: 8.9 },
          { category: 'Comfort', score: 8.9 },
          { category: 'Value', score: 8.7 },
          { category: 'Location', score: 9.1 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Old Town, Prague',
      },
      {
        name: 'Four Seasons Hotel Prague',
        starRating: 5,
        reviewScore: 9.4,
        reviewCount: 1120,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Vltava views', 'Fine dining', 'Gym', 'Concierge'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Deluxe river view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 350,
        photoSlug: 'fourseasons-prague',
        description: 'Prague\'s most luxurious hotel beautifully positioned on the Vltava River with stunning castle views. Offers refined elegance, fine dining, and a spa set in restored historic palaces overlooking Charles Bridge.',
        highlights: ['Prague Castle views', 'Fine dining restaurant', 'Vltava riverside spa'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.6 },
          { category: 'Facilities', score: 9.4 },
          { category: 'Cleanliness', score: 9.5 },
          { category: 'Comfort', score: 9.3 },
          { category: 'Value', score: 9.1 },
          { category: 'Location', score: 9.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Lesser Town, Prague',
      },
    ],
  },
  'London': {
    country: 'England',
    hotels: [
      {
        name: 'Point A Hotel London Kings Cross',
        starRating: 3,
        reviewScore: 7.9,
        reviewCount: 5640,
        reviewWord: 'Good',
        amenities: ['Wi-Fi', 'Smart TV', 'Air conditioning', '24h reception', 'Near Kings Cross'],
        distanceFromCentre: '1.2 km from centre',
        roomType: 'Twin room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 75,
        photoSlug: 'pointa-london',
        description: 'A practical budget hotel near Kings Cross station with clean, modern rooms. Perfect for travelers on a budget with convenient train connections to elsewhere in London and the UK.',
        highlights: ['Adjacent to Kings Cross station', 'Modern smart rooms', 'Central location for transport'],
        reviewBreakdown: [
          { category: 'Staff', score: 7.9 },
          { category: 'Facilities', score: 7.8 },
          { category: 'Cleanliness', score: 7.9 },
          { category: 'Comfort', score: 7.9 },
          { category: 'Value', score: 8.1 },
          { category: 'Location', score: 8.0 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Kings Cross, London',
      },
      {
        name: 'The Hoxton Shoreditch',
        starRating: 4,
        reviewScore: 8.5,
        reviewCount: 3210,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Restaurant', 'Bar', 'Coworking', 'Air conditioning'],
        distanceFromCentre: '2.0 km from centre',
        roomType: 'Cosy twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 175,
        photoSlug: 'hoxton-london',
        description: 'A trendy 4-star hotel in London\'s creative Shoreditch neighborhood with stylish rooms and vibrant dining scene. Perfect for design-conscious travelers with coworking spaces and a popular restaurant and bar.',
        highlights: ['Coworking spaces available', 'Trendy on-site restaurant and bar', 'Heart of creative Shoreditch'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.6 },
          { category: 'Facilities', score: 8.4 },
          { category: 'Cleanliness', score: 8.5 },
          { category: 'Comfort', score: 8.5 },
          { category: 'Value', score: 8.3 },
          { category: 'Location', score: 8.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Shoreditch, London',
      },
      {
        name: 'The Savoy',
        starRating: 5,
        reviewScore: 9.3,
        reviewCount: 2890,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Pool', 'Thames views', 'Fine dining', 'Butler', 'Gym'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Deluxe river view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 580,
        photoSlug: 'savoy-london',
        description: 'London\'s most iconic luxury hotel on the Thames with legendary service since 1889. Boasts stunning river views, fine dining, a world-class spa, and butler service in the heart of the West End.',
        highlights: ['Thames river views', 'Michelin-starred fine dining', 'Full butler service included'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.5 },
          { category: 'Facilities', score: 9.3 },
          { category: 'Cleanliness', score: 9.4 },
          { category: 'Comfort', score: 9.2 },
          { category: 'Value', score: 9.1 },
          { category: 'Location', score: 9.4 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'West End, London',
      },
    ],
  },
  'Edinburgh': {
    country: 'Scotland',
    hotels: [
      {
        name: 'CODE Pod Hostel Edinburgh',
        starRating: 3,
        reviewScore: 8.4,
        reviewCount: 2340,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Lounge', 'Kitchen', 'Lockers', '24h reception'],
        distanceFromCentre: '0.5 km from centre',
        roomType: 'Private pod room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 42,
        photoSlug: 'code-edinburgh',
        description: 'A modern pod hostel near Edinburgh\'s historic Royal Mile offering contemporary budget accommodation. Features a shared kitchen and lounge perfect for meeting fellow travelers.',
        highlights: ['Unique pod room design', 'Walking distance to Royal Mile', 'Communal kitchen available'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.5 },
          { category: 'Facilities', score: 8.3 },
          { category: 'Cleanliness', score: 8.4 },
          { category: 'Comfort', score: 8.2 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.5 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Old Town, Edinburgh',
      },
      {
        name: 'Apex Grassmarket Hotel',
        starRating: 4,
        reviewScore: 8.7,
        reviewCount: 2670,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Spa', 'Gym', 'Restaurant', 'Castle views', 'Air conditioning'],
        distanceFromCentre: '0.3 km from centre',
        roomType: 'Classic twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 140,
        photoSlug: 'apex-edinburgh',
        description: 'A contemporary 4-star hotel in Edinburgh\'s historic Grassmarket with stunning castle views. Features a spa, restaurant, and comfortable rooms in the heart of the Old Town near Edinburgh Castle.',
        highlights: ['Edinburgh Castle views', 'Historic Grassmarket location', 'Full-service spa'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.8 },
          { category: 'Facilities', score: 8.6 },
          { category: 'Cleanliness', score: 8.7 },
          { category: 'Comfort', score: 8.7 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.8 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Grassmarket, Edinburgh',
      },
      {
        name: 'The Balmoral – Rocco Forte',
        starRating: 5,
        reviewScore: 9.2,
        reviewCount: 1890,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Pool', 'Michelin restaurant', 'Castle views', 'Concierge', 'Gym'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Classic room with castle view',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 340,
        photoSlug: 'balmoral-edinburgh',
        description: 'Edinburgh\'s most prestigious luxury hotel with commanding views of the castle from its iconic clock tower. Offers fine dining, a world-class spa, and quintessential Scottish elegance.',
        highlights: ['Direct Edinburgh Castle views', 'Michelin-starred restaurant', 'Luxury spa with pool'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.3 },
          { category: 'Facilities', score: 9.2 },
          { category: 'Cleanliness', score: 9.3 },
          { category: 'Comfort', score: 9.1 },
          { category: 'Value', score: 9.0 },
          { category: 'Location', score: 9.3 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'City Centre, Edinburgh',
      },
    ],
  },
  'Dublin': {
    country: 'Ireland',
    hotels: [
      {
        name: 'Generator Dublin',
        starRating: 3,
        reviewScore: 7.9,
        reviewCount: 3120,
        reviewWord: 'Good',
        amenities: ['Wi-Fi', 'Bar', 'Café', 'Common area', '24h reception'],
        distanceFromCentre: '1.0 km from centre',
        roomType: 'Private quad room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 35,
        photoSlug: 'generator-dublin',
        description: 'A sociable hostel in Dublin with a vibrant bar and café scene perfect for backpackers. Located near the city center, it\'s a great budget option for meeting fellow travelers and exploring Dublin\'s pub culture.',
        highlights: ['Lively social bar', 'Walking distance to city center', 'Irish pub atmosphere'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.0 },
          { category: 'Facilities', score: 7.8 },
          { category: 'Cleanliness', score: 7.9 },
          { category: 'Comfort', score: 7.8 },
          { category: 'Value', score: 8.1 },
          { category: 'Location', score: 8.0 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Central Dublin, Dublin',
      },
      {
        name: 'The Dean Dublin',
        starRating: 4,
        reviewScore: 8.6,
        reviewCount: 2450,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Rooftop bar', 'Restaurant', 'Gym', 'Record players in rooms'],
        distanceFromCentre: '0.4 km from centre',
        roomType: 'Loft twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 155,
        photoSlug: 'dean-dublin',
        description: 'A stylish 4-star hotel in Dublin\'s heart with creative design elements and a buzzing rooftop bar. Features unique rooms with record players, fine dining, and a perfect base for exploring Temple Bar and beyond.',
        highlights: ['Rooftop bar with city views', 'Unique record players in rooms', 'Heart of Temple Bar district'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.7 },
          { category: 'Facilities', score: 8.5 },
          { category: 'Cleanliness', score: 8.6 },
          { category: 'Comfort', score: 8.6 },
          { category: 'Value', score: 8.4 },
          { category: 'Location', score: 8.7 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Temple Bar, Dublin',
      },
      {
        name: 'The Shelbourne – Autograph Collection',
        starRating: 5,
        reviewScore: 9.1,
        reviewCount: 1780,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Pool', 'Fine dining', 'St Stephen\'s Green views', 'Concierge'],
        distanceFromCentre: '0.2 km from centre',
        roomType: 'Deluxe park view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 390,
        photoSlug: 'shelbourne-dublin',
        description: 'Dublin\'s most prestigious hotel on St Stephen\'s Green with historic elegance and contemporary luxury. Overlooks the beautiful city park and features fine dining, spa, and impeccable service.',
        highlights: ['St Stephen\'s Green park views', 'Michelin-starred fine dining', 'Full-service spa with pool'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.2 },
          { category: 'Facilities', score: 9.1 },
          { category: 'Cleanliness', score: 9.2 },
          { category: 'Comfort', score: 9.0 },
          { category: 'Value', score: 8.9 },
          { category: 'Location', score: 9.2 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'St Stephen\'s Green, Dublin',
      },
    ],
  },
  'New York': {
    country: 'USA',
    hotels: [
      {
        name: 'Pod 51 Hotel',
        starRating: 3,
        reviewScore: 7.7,
        reviewCount: 4870,
        reviewWord: 'Good',
        amenities: ['Wi-Fi', 'Rooftop', 'Café', 'Air conditioning', 'Near Midtown'],
        distanceFromCentre: '1.5 km from centre',
        roomType: 'Queen pod room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 95,
        photoSlug: 'pod51-nyc',
        description: 'A budget-friendly hotel near Grand Central Terminal with modern pod-style rooms and a fun rooftop bar. Perfect for solo travelers and groups looking for affordable accommodation in Midtown Manhattan.',
        highlights: ['Rooftop bar with city views', 'Steps from Grand Central', 'Budget-friendly pods'],
        reviewBreakdown: [
          { category: 'Staff', score: 7.8 },
          { category: 'Facilities', score: 7.6 },
          { category: 'Cleanliness', score: 7.7 },
          { category: 'Comfort', score: 7.5 },
          { category: 'Value', score: 8.0 },
          { category: 'Location', score: 7.8 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Midtown Manhattan, New York',
      },
      {
        name: 'Arlo Midtown',
        starRating: 4,
        reviewScore: 8.3,
        reviewCount: 2340,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Rooftop bar', 'Restaurant', 'Gym', 'Near Times Square'],
        distanceFromCentre: '0.5 km from centre',
        roomType: 'King city view room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'mid-range',
        basePricePerNight: 220,
        photoSlug: 'arlo-nyc',
        description: 'A contemporary 4-star hotel in the heart of Times Square with stylish rooms and rooftop bar. Perfect for experiencing NYC with great restaurants and direct access to Broadway theaters and attractions.',
        highlights: ['Rooftop bar with skyline views', 'Adjacent to Times Square', 'Steps from Broadway theaters'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.4 },
          { category: 'Facilities', score: 8.2 },
          { category: 'Cleanliness', score: 8.3 },
          { category: 'Comfort', score: 8.3 },
          { category: 'Value', score: 8.1 },
          { category: 'Location', score: 8.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Times Square, New York',
      },
      {
        name: 'The Plaza Hotel',
        starRating: 5,
        reviewScore: 9.0,
        reviewCount: 3150,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Gym', 'Fine dining', 'Central Park views', 'Butler', 'Concierge'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Deluxe park view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 750,
        photoSlug: 'plaza-nyc',
        description: 'An iconic NYC luxury hotel overlooking Central Park with legendary elegance and impeccable service. Offers Michelin-starred dining, world-class spa, and butler service in a historic palace setting.',
        highlights: ['Central Park views', 'Michelin-starred fine dining', 'Personal butler service'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.2 },
          { category: 'Facilities', score: 9.0 },
          { category: 'Cleanliness', score: 9.1 },
          { category: 'Comfort', score: 9.0 },
          { category: 'Value', score: 8.7 },
          { category: 'Location', score: 9.1 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Fifth Avenue, New York',
      },
    ],
  },
  'Cancun': {
    country: 'Mexico',
    hotels: [
      {
        name: 'Hostel Mundo Joven Cancún',
        starRating: 3,
        reviewScore: 7.6,
        reviewCount: 1890,
        reviewWord: 'Good',
        amenities: ['Wi-Fi', 'Pool', 'Bar', 'Common area', '24h reception'],
        distanceFromCentre: '2.0 km from centre',
        roomType: 'Private room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 22,
        photoSlug: 'mundo-cancun',
        description: 'A budget-friendly hostel with a fun pool and social bar scene in downtown Cancun. Perfect for young travelers looking for an affordable beach vacation with easy access to nightlife and water sports.',
        highlights: ['Swimming pool on-site', 'Social bar atmosphere', 'Close to downtown Cancun'],
        reviewBreakdown: [
          { category: 'Staff', score: 7.7 },
          { category: 'Facilities', score: 7.5 },
          { category: 'Cleanliness', score: 7.5 },
          { category: 'Comfort', score: 7.4 },
          { category: 'Value', score: 7.8 },
          { category: 'Location', score: 7.7 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Downtown Cancun, Cancun',
      },
      {
        name: 'Hyatt Ziva Cancún',
        starRating: 4,
        reviewScore: 8.8,
        reviewCount: 3450,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'All-inclusive', 'Beach', 'Pool', 'Spa', 'Multiple restaurants'],
        distanceFromCentre: '0.5 km from hotel zone',
        roomType: 'Ocean view twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 195,
        photoSlug: 'ziva-cancun',
        description: 'An all-inclusive 4-star resort in Cancun\'s Hotel Zone with direct beach access and multiple restaurants. Perfect for families with a water park, spa, and variety of water sports activities included.',
        highlights: ['All-inclusive with beach access', 'Multiple restaurants and bars', 'Water park and spa facilities'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.9 },
          { category: 'Facilities', score: 8.8 },
          { category: 'Cleanliness', score: 8.8 },
          { category: 'Comfort', score: 8.7 },
          { category: 'Value', score: 8.6 },
          { category: 'Location', score: 8.9 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Hotel Zone, Cancun',
      },
      {
        name: 'Ritz-Carlton Cancún',
        starRating: 5,
        reviewScore: 9.2,
        reviewCount: 2100,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'Private beach', 'Fine dining', 'Pool', 'Concierge', 'Gym'],
        distanceFromCentre: '0.3 km from hotel zone',
        roomType: 'Oceanfront deluxe room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 450,
        photoSlug: 'ritz-cancun',
        description: 'Cancun\'s premier luxury resort with oceanfront elegance, private beach, and world-class service. Features fine dining, a full-service spa, and stunning Caribbean views perfect for a romantic escape.',
        highlights: ['Private beach access', 'Michelin-standard fine dining', 'Caribbean oceanfront spa'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.3 },
          { category: 'Facilities', score: 9.2 },
          { category: 'Cleanliness', score: 9.3 },
          { category: 'Comfort', score: 9.1 },
          { category: 'Value', score: 9.0 },
          { category: 'Location', score: 9.2 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Hotel Zone, Cancun',
      },
    ],
  },
  'Dubai': {
    country: 'UAE',
    hotels: [
      {
        name: 'Rove Downtown Dubai',
        starRating: 3,
        reviewScore: 8.4,
        reviewCount: 4560,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Pool', 'Gym', 'Restaurant', 'Near Burj Khalifa'],
        distanceFromCentre: '0.5 km from centre',
        roomType: 'Rover twin room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 55,
        photoSlug: 'rove-dubai',
        description: 'A stylish budget hotel near Dubai\'s iconic Burj Khalifa with modern rooms and facilities. Perfect for budget-conscious travelers wanting to experience Dubai\'s downtown area and nearby attractions.',
        highlights: ['Near Burj Khalifa', 'Modern budget accommodation', 'Pool and gym facilities'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.5 },
          { category: 'Facilities', score: 8.3 },
          { category: 'Cleanliness', score: 8.4 },
          { category: 'Comfort', score: 8.3 },
          { category: 'Value', score: 8.5 },
          { category: 'Location', score: 8.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Downtown Dubai, Dubai',
      },
      {
        name: 'Address Downtown Dubai',
        starRating: 4,
        reviewScore: 8.9,
        reviewCount: 2870,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Pool', 'Spa', 'Restaurant', 'Burj Khalifa views', 'Gym'],
        distanceFromCentre: '0.1 km from centre',
        roomType: 'Fountain view room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 210,
        photoSlug: 'address-dubai',
        description: 'A contemporary 4-star hotel with views of the Burj Khalifa and Dubai Fountain from the rooms. Offers spa facilities, multiple dining options, and a perfect base for exploring downtown Dubai.',
        highlights: ['Burj Khalifa views', 'Dubai Fountain views', 'Spa with pool'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.9 },
          { category: 'Facilities', score: 8.9 },
          { category: 'Cleanliness', score: 8.9 },
          { category: 'Comfort', score: 8.9 },
          { category: 'Value', score: 8.8 },
          { category: 'Location', score: 9.0 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Downtown Dubai, Dubai',
      },
      {
        name: 'Burj Al Arab Jumeirah',
        starRating: 5,
        reviewScore: 9.5,
        reviewCount: 1560,
        reviewWord: 'Exceptional',
        amenities: ['Wi-Fi', 'Private beach', 'Spa', 'Butler', 'Fine dining', 'Pool', 'Helipad'],
        distanceFromCentre: '5.0 km from centre',
        roomType: 'Deluxe suite',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 1200,
        photoSlug: 'burj-dubai',
        description: 'Dubai\'s most iconic luxury hotel shaped like a sail, offering unparalleled extravagance on a private island. Features Michelin-starred dining, personal butler service, and access to pristine private beaches.',
        highlights: ['Private island location', 'Michelin-starred fine dining', 'Personal butler service'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.7 },
          { category: 'Facilities', score: 9.6 },
          { category: 'Cleanliness', score: 9.6 },
          { category: 'Comfort', score: 9.5 },
          { category: 'Value', score: 9.2 },
          { category: 'Location', score: 9.4 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Jumeirah, Dubai',
      },
    ],
  },
  'Bangkok': {
    country: 'Thailand',
    hotels: [
      {
        name: 'NapPark Hostel @ Khao San',
        starRating: 3,
        reviewScore: 8.0,
        reviewCount: 3890,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Café', 'Lounge', 'Air conditioning', 'Near Khao San Road'],
        distanceFromCentre: '2.0 km from centre',
        roomType: 'Private room (4 beds)',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 15,
        photoSlug: 'nappark-bangkok',
        description: 'A budget hostel on Bangkok\'s famous Khao San Road with a relaxed vibe and social atmosphere. Perfect for backpackers with easy access to temples, night markets, and Bangkok\'s vibrant nightlife.',
        highlights: ['Located on Khao San Road', 'Social lounge and café', 'Walking distance to temples'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.1 },
          { category: 'Facilities', score: 7.9 },
          { category: 'Cleanliness', score: 8.0 },
          { category: 'Comfort', score: 7.9 },
          { category: 'Value', score: 8.2 },
          { category: 'Location', score: 8.1 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Khao San, Bangkok',
      },
      {
        name: 'Centara Grand at CentralWorld',
        starRating: 4,
        reviewScore: 8.7,
        reviewCount: 5230,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Pool', 'Spa', 'Restaurant', 'Sky bar', 'Gym', 'Air conditioning'],
        distanceFromCentre: '0.3 km from centre',
        roomType: 'Deluxe twin room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 85,
        photoSlug: 'centara-bangkok',
        description: 'A luxurious 4-star hotel in Bangkok\'s largest shopping mall with a rooftop sky bar and spa. Perfect for exploring the city with direct access to CentralWorld shopping and surrounded by restaurants.',
        highlights: ['Rooftop sky bar', 'Integrated with CentralWorld mall', 'Full-service spa'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.8 },
          { category: 'Facilities', score: 8.7 },
          { category: 'Cleanliness', score: 8.7 },
          { category: 'Comfort', score: 8.6 },
          { category: 'Value', score: 8.6 },
          { category: 'Location', score: 8.8 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Ratchaprasong, Bangkok',
      },
      {
        name: 'Mandarin Oriental Bangkok',
        starRating: 5,
        reviewScore: 9.4,
        reviewCount: 1890,
        reviewWord: 'Superb',
        amenities: ['Wi-Fi', 'Spa', 'River views', 'Fine dining', 'Pool', 'Butler', 'Concierge'],
        distanceFromCentre: '1.5 km from centre',
        roomType: 'River wing deluxe room',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 280,
        photoSlug: 'mandarin-bangkok',
        description: 'Bangkok\'s most storied luxury hotel on the Chao Phraya River offering timeless elegance and impeccable service. Features Michelin-recognized dining, Thai massage spa, and stunning river views.',
        highlights: ['Chao Phraya River views', 'Michelin-standard fine dining', 'Traditional Thai spa'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.5 },
          { category: 'Facilities', score: 9.4 },
          { category: 'Cleanliness', score: 9.4 },
          { category: 'Comfort', score: 9.3 },
          { category: 'Value', score: 9.2 },
          { category: 'Location', score: 9.5 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Silom, Bangkok',
      },
    ],
  },
  'Bali': {
    country: 'Indonesia',
    hotels: [
      {
        name: 'Kos One Hostel Seminyak',
        starRating: 3,
        reviewScore: 8.1,
        reviewCount: 2340,
        reviewWord: 'Very good',
        amenities: ['Wi-Fi', 'Pool', 'Bar', 'Air conditioning', 'Near beach'],
        distanceFromCentre: '1.0 km from centre',
        roomType: 'Private twin room',
        freeCancellation: true,
        breakfastIncluded: false,
        tier: 'budget',
        basePricePerNight: 18,
        photoSlug: 'kosone-bali',
        description: 'A laid-back budget hostel in Seminyak with a pool and social bar perfect for beach lovers. Walking distance to Seminyak Beach with easy access to restaurants, bars, and water sports.',
        highlights: ['Walking distance to beach', 'Pool and social bar', 'Near restaurants and nightlife'],
        reviewBreakdown: [
          { category: 'Staff', score: 8.2 },
          { category: 'Facilities', score: 8.0 },
          { category: 'Cleanliness', score: 8.1 },
          { category: 'Comfort', score: 8.0 },
          { category: 'Value', score: 8.3 },
          { category: 'Location', score: 8.2 },
        ],
        checkInTime: '16:00',
        checkOutTime: '11:00',
        neighbourhood: 'Seminyak, Bali',
      },
      {
        name: 'Alila Seminyak',
        starRating: 4,
        reviewScore: 8.9,
        reviewCount: 1870,
        reviewWord: 'Excellent',
        amenities: ['Wi-Fi', 'Beach', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym'],
        distanceFromCentre: '0.3 km from beach',
        roomType: 'Deluxe ocean suite',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'mid-range',
        basePricePerNight: 140,
        photoSlug: 'alila-bali',
        description: 'A contemporary 4-star resort in Seminyak steps from the beach with ocean views and modern design. Features a spa, restaurant, and easy access to Seminyak\'s vibrant beach clubs and dining scene.',
        highlights: ['Direct beach access', 'Ocean view rooms', 'Spa and restaurant'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.0 },
          { category: 'Facilities', score: 8.9 },
          { category: 'Cleanliness', score: 8.9 },
          { category: 'Comfort', score: 8.8 },
          { category: 'Value', score: 8.8 },
          { category: 'Location', score: 9.1 },
        ],
        checkInTime: '15:00',
        checkOutTime: '11:00',
        neighbourhood: 'Seminyak, Bali',
      },
      {
        name: 'Four Seasons Resort Bali at Jimbaran Bay',
        starRating: 5,
        reviewScore: 9.5,
        reviewCount: 1230,
        reviewWord: 'Exceptional',
        amenities: ['Wi-Fi', 'Private villas', 'Spa', 'Beach', 'Fine dining', 'Pool', 'Concierge'],
        distanceFromCentre: '0.1 km from beach',
        roomType: 'Garden villa',
        freeCancellation: true,
        breakfastIncluded: true,
        tier: 'premium',
        basePricePerNight: 450,
        photoSlug: 'fourseasons-bali',
        description: 'Bali\'s most luxurious resort with private villas set on pristine Jimbaran Beach overlooking the Indian Ocean. Features fine dining, world-class spa, and unparalleled seclusion for the ultimate tropical escape.',
        highlights: ['Private villa accommodations', 'Direct Jimbaran Beach access', 'Fine dining with ocean views'],
        reviewBreakdown: [
          { category: 'Staff', score: 9.6 },
          { category: 'Facilities', score: 9.5 },
          { category: 'Cleanliness', score: 9.5 },
          { category: 'Comfort', score: 9.5 },
          { category: 'Value', score: 9.3 },
          { category: 'Location', score: 9.6 },
        ],
        checkInTime: '15:00',
        checkOutTime: '12:00',
        neighbourhood: 'Jimbaran, Bali',
      },
    ],
  },
}

// =====================================================
// SEARCH FUNCTION
// =====================================================

interface SearchParams {
  destination: string
  checkIn: string     // YYYY-MM-DD
  checkOut: string    // YYYY-MM-DD
  guests: number
  rooms?: number
}

/**
 * Search hotels for a destination.
 *
 * Currently returns mock data structured like the Booking.com Demand API response.
 * To go live: replace this function's internals with a real API call to
 * https://demandapi.booking.com/3.1/accommodations/search
 */
export async function searchHotels(params: SearchParams): Promise<HotelOption[]> {
  const { destination, checkIn, checkOut, guests, rooms: roomsParam } = params

  // Normalise destination (strip country suffix like "Barcelona, Spain")
  const city = destination.split(',')[0].trim()

  // Calculate nights
  const checkInDate = new Date(checkIn)
  const checkOutDate = new Date(checkOut)
  const nights = Math.max(1, Math.round((checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 60 * 60 * 24)))

  // Estimate rooms needed (2 guests per room, rounded up)
  const rooms = roomsParam || Math.ceil(guests / 2)

  // Simulate network delay (1-2 seconds)
  await new Promise(r => setTimeout(r, 1000 + Math.random() * 1000))

  // Find hotel data for this city
  const cityData = HOTEL_DATA[city]

  if (!cityData) {
    // Generate generic hotels for destinations we don't have specific data for
    return generateGenericHotels(city, destination, nights, guests, rooms, checkIn, checkOut)
  }

  // Build hotel options with calculated pricing
  return cityData.hotels.map((hotel, index) => {
    // Add slight price variation for realism (±10%)
    const variation = 0.9 + Math.random() * 0.2
    const adjustedPrice = Math.round(hotel.basePricePerNight * variation)
    const totalPrice = adjustedPrice * nights * rooms

    const tierLabels: Record<string, string> = {
      'budget': 'Budget-friendly',
      'mid-range': 'Best for groups',
      'premium': 'Premium',
    }

    return {
      id: `hotel_${city.toLowerCase().replace(/\s+/g, '')}_${index}`,
      name: hotel.name,
      starRating: hotel.starRating,
      reviewScore: hotel.reviewScore,
      reviewCount: hotel.reviewCount,
      reviewWord: hotel.reviewWord,
      address: `${hotel.distanceFromCentre}`,
      city: city,
      country: cityData.country,
      photoUrl: `/api/hotels/photo?slug=${hotel.photoSlug}`,
      amenities: hotel.amenities,
      distanceFromCentre: hotel.distanceFromCentre,
      pricePerNight: adjustedPrice * rooms,
      totalPrice,
      currency: 'GBP',
      nights,
      guests,
      rooms,
      roomType: hotel.roomType,
      freeCancellation: hotel.freeCancellation,
      breakfastIncluded: hotel.breakfastIncluded,
      bookingUrl: generateBookingUrl(city, checkIn, checkOut, guests),
      tier: hotel.tier,
      tierLabel: tierLabels[hotel.tier],
      description: hotel.description,
      highlights: hotel.highlights,
      reviewBreakdown: hotel.reviewBreakdown,
      checkInTime: hotel.checkInTime,
      checkOutTime: hotel.checkOutTime,
      neighbourhood: hotel.neighbourhood,
    }
  })
}

/**
 * Generate generic hotel options for cities without specific data
 */
function generateGenericHotels(city: string, fullDestination: string, nights: number, guests: number, rooms: number, checkIn: string = '', checkOut: string = ''): HotelOption[] {
  const country = fullDestination.includes(',') ? fullDestination.split(',')[1].trim() : ''

  const templates = [
    {
      namePrefix: 'Central',
      nameSuffix: 'Hostel',
      starRating: 3,
      reviewScore: 7.8,
      reviewCount: 1200 + Math.floor(Math.random() * 2000),
      reviewWord: 'Good',
      amenities: ['Wi-Fi', 'Bar', 'Common area', '24h reception'],
      distanceFromCentre: '1.0 km from centre',
      roomType: 'Private room (4 beds)',
      tier: 'budget' as const,
      basePricePerNight: 30,
      description: 'A friendly budget hostel in the heart of the city with a social bar and common areas. Perfect for backpackers and solo travelers looking for an affordable and fun place to meet other guests.',
      highlights: ['Social bar and common areas', 'Central location', 'Affordable rates'],
      reviewBreakdown: [
        { category: 'Staff', score: 7.9 },
        { category: 'Facilities', score: 7.7 },
        { category: 'Cleanliness', score: 7.8 },
        { category: 'Comfort', score: 7.6 },
        { category: 'Value', score: 8.1 },
        { category: 'Location', score: 7.9 },
      ],
      checkInTime: '16:00',
      checkOutTime: '11:00',
      neighbourhood: 'City Centre',
    },
    {
      namePrefix: 'Hotel',
      nameSuffix: 'Grand',
      starRating: 4,
      reviewScore: 8.5,
      reviewCount: 1500 + Math.floor(Math.random() * 2000),
      reviewWord: 'Very good',
      amenities: ['Wi-Fi', 'Restaurant', 'Bar', 'Gym', 'Air conditioning'],
      distanceFromCentre: '0.4 km from centre',
      roomType: 'Twin room',
      tier: 'mid-range' as const,
      basePricePerNight: 120,
      description: 'A comfortable 4-star hotel offering excellent value with modern amenities and convenient location. Features dining facilities, fitness center, and friendly service.',
      highlights: ['Restaurant and bar', 'Fitness facilities', 'Near major attractions'],
      reviewBreakdown: [
        { category: 'Staff', score: 8.6 },
        { category: 'Facilities', score: 8.4 },
        { category: 'Cleanliness', score: 8.5 },
        { category: 'Comfort', score: 8.4 },
        { category: 'Value', score: 8.3 },
        { category: 'Location', score: 8.6 },
      ],
      checkInTime: '15:00',
      checkOutTime: '11:00',
      neighbourhood: 'City Centre',
    },
    {
      namePrefix: 'The',
      nameSuffix: 'Palace Hotel & Spa',
      starRating: 5,
      reviewScore: 9.1,
      reviewCount: 800 + Math.floor(Math.random() * 1000),
      reviewWord: 'Superb',
      amenities: ['Wi-Fi', 'Spa', 'Pool', 'Fine dining', 'Gym', 'Concierge'],
      distanceFromCentre: '0.2 km from centre',
      roomType: 'Deluxe room',
      tier: 'premium' as const,
      basePricePerNight: 300,
      description: 'A luxurious 5-star hotel offering world-class service and premium amenities. Features fine dining, full-service spa, pool, and personalized concierge services.',
      highlights: ['Fine dining restaurant', 'Spa and pool', 'Concierge service'],
      reviewBreakdown: [
        { category: 'Staff', score: 9.2 },
        { category: 'Facilities', score: 9.1 },
        { category: 'Cleanliness', score: 9.2 },
        { category: 'Comfort', score: 9.0 },
        { category: 'Value', score: 8.8 },
        { category: 'Location', score: 9.1 },
      ],
      checkInTime: '15:00',
      checkOutTime: '12:00',
      neighbourhood: 'City Centre',
    },
  ]

  const tierLabels: Record<string, string> = {
    'budget': 'Budget-friendly',
    'mid-range': 'Best for groups',
    'premium': 'Premium',
  }

  return templates.map((t, index) => {
    const variation = 0.9 + Math.random() * 0.2
    const adjustedPrice = Math.round(t.basePricePerNight * variation)
    const totalPrice = adjustedPrice * nights * rooms
    const name = t.tier === 'mid-range'
      ? `${t.namePrefix} ${city} ${t.nameSuffix}`
      : t.tier === 'budget'
        ? `${city} ${t.namePrefix} ${t.nameSuffix}`
        : `${t.namePrefix} ${city} ${t.nameSuffix}`

    return {
      id: `hotel_${city.toLowerCase().replace(/\s+/g, '')}_${index}`,
      name,
      starRating: t.starRating,
      reviewScore: t.reviewScore,
      reviewCount: t.reviewCount,
      reviewWord: t.reviewWord,
      address: t.distanceFromCentre,
      city,
      country,
      photoUrl: `/api/hotels/photo?slug=generic-${t.tier}`,
      amenities: t.amenities,
      distanceFromCentre: t.distanceFromCentre,
      pricePerNight: adjustedPrice * rooms,
      totalPrice,
      currency: 'GBP',
      nights,
      guests,
      rooms,
      roomType: t.roomType,
      freeCancellation: true,
      breakfastIncluded: t.tier !== 'budget',
      bookingUrl: generateBookingUrl(city, checkIn, checkOut, guests),
      tier: t.tier,
      tierLabel: tierLabels[t.tier],
      description: t.description,
      highlights: t.highlights,
      reviewBreakdown: t.reviewBreakdown,
      checkInTime: t.checkInTime,
      checkOutTime: t.checkOutTime,
      neighbourhood: t.neighbourhood,
    }

  })
}

/**
 * Generate a Booking.com affiliate URL for a destination.
 * When you have real credentials, this will include your affiliate ID for tracking.
 */
function generateBookingUrl(city: string, checkIn: string, checkOut: string, guests: number): string {
  const encodedCity = encodeURIComponent(city)
  const affiliateId = BOOKING_AFFILIATE_ID || 'PLACEHOLDER'

  // Real Booking.com search URL format with affiliate tracking
  return `https://www.booking.com/searchresults.html?ss=${encodedCity}&checkin=${checkIn}&checkout=${checkOut}&group_adults=${guests}&no_rooms=${Math.ceil(guests / 2)}&aid=${affiliateId}`
}

/**
 * Check if we have hotel data for a given city
 */
export function hasHotelData(city: string): boolean {
  const normalised = city.split(',')[0].trim()
  return normalised in HOTEL_DATA
}

/**
 * Get all cities that have specific hotel data
 */
export function getHotelCities(): string[] {
  return Object.keys(HOTEL_DATA)
}
