export type Region = 'anywhere' | 'europe' | 'uk' | 'usa' | 'asia' | 'caribbean' | 'middle_east' | 'oceania' | 'south_america' | 'canada' | 'africa'

export interface Destination {
  city: string
  country: string
  region: Region[]
}

// Curated list of popular travel destinations
// Each city can belong to multiple region tags
export const destinations: Destination[] = [
  // UK
  { city: 'London', country: 'England', region: ['uk', 'europe'] },
  { city: 'Edinburgh', country: 'Scotland', region: ['uk', 'europe'] },
  { city: 'Manchester', country: 'England', region: ['uk', 'europe'] },
  { city: 'Birmingham', country: 'England', region: ['uk', 'europe'] },
  { city: 'Liverpool', country: 'England', region: ['uk', 'europe'] },
  { city: 'Bristol', country: 'England', region: ['uk', 'europe'] },
  { city: 'Glasgow', country: 'Scotland', region: ['uk', 'europe'] },
  { city: 'Cardiff', country: 'Wales', region: ['uk', 'europe'] },
  { city: 'Belfast', country: 'Northern Ireland', region: ['uk', 'europe'] },
  { city: 'Leeds', country: 'England', region: ['uk', 'europe'] },
  { city: 'Newcastle', country: 'England', region: ['uk', 'europe'] },
  { city: 'Bath', country: 'England', region: ['uk', 'europe'] },
  { city: 'York', country: 'England', region: ['uk', 'europe'] },
  { city: 'Brighton', country: 'England', region: ['uk', 'europe'] },
  { city: 'Oxford', country: 'England', region: ['uk', 'europe'] },
  { city: 'Cambridge', country: 'England', region: ['uk', 'europe'] },
  { city: 'Inverness', country: 'Scotland', region: ['uk', 'europe'] },
  { city: 'Aberdeen', country: 'Scotland', region: ['uk', 'europe'] },
  { city: 'Bournemouth', country: 'England', region: ['uk', 'europe'] },
  { city: 'Nottingham', country: 'England', region: ['uk', 'europe'] },
  { city: 'Cornwall', country: 'England', region: ['uk', 'europe'] },
  { city: 'Lake District', country: 'England', region: ['uk', 'europe'] },
  { city: 'Jersey', country: 'Channel Islands', region: ['uk', 'europe'] },
  { city: 'Isle of Man', country: 'Isle of Man', region: ['uk', 'europe'] },

  // Spain (expanded)
  { city: 'Barcelona', country: 'Spain', region: ['europe'] },
  { city: 'Madrid', country: 'Spain', region: ['europe'] },
  { city: 'Ibiza', country: 'Spain', region: ['europe'] },
  { city: 'Malaga', country: 'Spain', region: ['europe'] },
  { city: 'Seville', country: 'Spain', region: ['europe'] },
  { city: 'Valencia', country: 'Spain', region: ['europe'] },
  { city: 'Tenerife', country: 'Spain', region: ['europe'] },
  { city: 'Majorca', country: 'Spain', region: ['europe'] },
  { city: 'Bilbao', country: 'Spain', region: ['europe'] },
  { city: 'San Sebastian', country: 'Spain', region: ['europe'] },
  { city: 'Granada', country: 'Spain', region: ['europe'] },
  { city: 'Alicante', country: 'Spain', region: ['europe'] },
  { city: 'Lanzarote', country: 'Spain', region: ['europe'] },
  { city: 'Gran Canaria', country: 'Spain', region: ['europe'] },
  { city: 'Fuerteventura', country: 'Spain', region: ['europe'] },
  { city: 'Menorca', country: 'Spain', region: ['europe'] },
  { city: 'Marbella', country: 'Spain', region: ['europe'] },
  { city: 'Cadiz', country: 'Spain', region: ['europe'] },

  // France (expanded)
  { city: 'Paris', country: 'France', region: ['europe'] },
  { city: 'Nice', country: 'France', region: ['europe'] },
  { city: 'Lyon', country: 'France', region: ['europe'] },
  { city: 'Marseille', country: 'France', region: ['europe'] },
  { city: 'Bordeaux', country: 'France', region: ['europe'] },
  { city: 'Toulouse', country: 'France', region: ['europe'] },
  { city: 'Strasbourg', country: 'France', region: ['europe'] },
  { city: 'Montpellier', country: 'France', region: ['europe'] },
  { city: 'Cannes', country: 'France', region: ['europe'] },
  { city: 'Saint-Tropez', country: 'France', region: ['europe'] },
  { city: 'Corsica', country: 'France', region: ['europe'] },
  { city: 'Chamonix', country: 'France', region: ['europe'] },

  // Italy (expanded)
  { city: 'Rome', country: 'Italy', region: ['europe'] },
  { city: 'Milan', country: 'Italy', region: ['europe'] },
  { city: 'Florence', country: 'Italy', region: ['europe'] },
  { city: 'Venice', country: 'Italy', region: ['europe'] },
  { city: 'Naples', country: 'Italy', region: ['europe'] },
  { city: 'Amalfi Coast', country: 'Italy', region: ['europe'] },
  { city: 'Lake Como', country: 'Italy', region: ['europe'] },
  { city: 'Sardinia', country: 'Italy', region: ['europe'] },
  { city: 'Sicily', country: 'Italy', region: ['europe'] },
  { city: 'Bologna', country: 'Italy', region: ['europe'] },
  { city: 'Turin', country: 'Italy', region: ['europe'] },
  { city: 'Cinque Terre', country: 'Italy', region: ['europe'] },
  { city: 'Puglia', country: 'Italy', region: ['europe'] },
  { city: 'Verona', country: 'Italy', region: ['europe'] },
  { city: 'Pisa', country: 'Italy', region: ['europe'] },

  // Germany (expanded)
  { city: 'Berlin', country: 'Germany', region: ['europe'] },
  { city: 'Munich', country: 'Germany', region: ['europe'] },
  { city: 'Hamburg', country: 'Germany', region: ['europe'] },
  { city: 'Frankfurt', country: 'Germany', region: ['europe'] },
  { city: 'Cologne', country: 'Germany', region: ['europe'] },
  { city: 'Dusseldorf', country: 'Germany', region: ['europe'] },
  { city: 'Stuttgart', country: 'Germany', region: ['europe'] },
  { city: 'Dresden', country: 'Germany', region: ['europe'] },

  // Netherlands & Belgium
  { city: 'Amsterdam', country: 'Netherlands', region: ['europe'] },
  { city: 'Rotterdam', country: 'Netherlands', region: ['europe'] },
  { city: 'The Hague', country: 'Netherlands', region: ['europe'] },
  { city: 'Brussels', country: 'Belgium', region: ['europe'] },
  { city: 'Bruges', country: 'Belgium', region: ['europe'] },
  { city: 'Ghent', country: 'Belgium', region: ['europe'] },
  { city: 'Antwerp', country: 'Belgium', region: ['europe'] },

  // Central Europe
  { city: 'Prague', country: 'Czech Republic', region: ['europe'] },
  { city: 'Vienna', country: 'Austria', region: ['europe'] },
  { city: 'Salzburg', country: 'Austria', region: ['europe'] },
  { city: 'Innsbruck', country: 'Austria', region: ['europe'] },
  { city: 'Budapest', country: 'Hungary', region: ['europe'] },
  { city: 'Krakow', country: 'Poland', region: ['europe'] },
  { city: 'Warsaw', country: 'Poland', region: ['europe'] },
  { city: 'Gdansk', country: 'Poland', region: ['europe'] },
  { city: 'Wroclaw', country: 'Poland', region: ['europe'] },
  { city: 'Bratislava', country: 'Slovakia', region: ['europe'] },
  { city: 'Ljubljana', country: 'Slovenia', region: ['europe'] },
  { city: 'Lake Bled', country: 'Slovenia', region: ['europe'] },

  // Portugal (expanded)
  { city: 'Lisbon', country: 'Portugal', region: ['europe'] },
  { city: 'Porto', country: 'Portugal', region: ['europe'] },
  { city: 'Algarve', country: 'Portugal', region: ['europe'] },
  { city: 'Madeira', country: 'Portugal', region: ['europe'] },
  { city: 'Azores', country: 'Portugal', region: ['europe'] },

  // Greece (expanded)
  { city: 'Athens', country: 'Greece', region: ['europe'] },
  { city: 'Santorini', country: 'Greece', region: ['europe'] },
  { city: 'Mykonos', country: 'Greece', region: ['europe'] },
  { city: 'Crete', country: 'Greece', region: ['europe'] },
  { city: 'Corfu', country: 'Greece', region: ['europe'] },
  { city: 'Rhodes', country: 'Greece', region: ['europe'] },
  { city: 'Thessaloniki', country: 'Greece', region: ['europe'] },
  { city: 'Zakynthos', country: 'Greece', region: ['europe'] },
  { city: 'Kefalonia', country: 'Greece', region: ['europe'] },
  { city: 'Kos', country: 'Greece', region: ['europe'] },

  // Nordics & Baltics
  { city: 'Dublin', country: 'Ireland', region: ['europe'] },
  { city: 'Galway', country: 'Ireland', region: ['europe'] },
  { city: 'Cork', country: 'Ireland', region: ['europe'] },
  { city: 'Copenhagen', country: 'Denmark', region: ['europe'] },
  { city: 'Stockholm', country: 'Sweden', region: ['europe'] },
  { city: 'Gothenburg', country: 'Sweden', region: ['europe'] },
  { city: 'Oslo', country: 'Norway', region: ['europe'] },
  { city: 'Bergen', country: 'Norway', region: ['europe'] },
  { city: 'Tromso', country: 'Norway', region: ['europe'] },
  { city: 'Helsinki', country: 'Finland', region: ['europe'] },
  { city: 'Lapland', country: 'Finland', region: ['europe'] },
  { city: 'Reykjavik', country: 'Iceland', region: ['europe'] },
  { city: 'Tallinn', country: 'Estonia', region: ['europe'] },
  { city: 'Riga', country: 'Latvia', region: ['europe'] },
  { city: 'Vilnius', country: 'Lithuania', region: ['europe'] },

  // Switzerland
  { city: 'Zurich', country: 'Switzerland', region: ['europe'] },
  { city: 'Geneva', country: 'Switzerland', region: ['europe'] },
  { city: 'Lucerne', country: 'Switzerland', region: ['europe'] },
  { city: 'Interlaken', country: 'Switzerland', region: ['europe'] },
  { city: 'Zermatt', country: 'Switzerland', region: ['europe'] },

  // Balkans & Eastern Europe
  { city: 'Dubrovnik', country: 'Croatia', region: ['europe'] },
  { city: 'Split', country: 'Croatia', region: ['europe'] },
  { city: 'Zagreb', country: 'Croatia', region: ['europe'] },
  { city: 'Hvar', country: 'Croatia', region: ['europe'] },
  { city: 'Montenegro', country: 'Montenegro', region: ['europe'] },
  { city: 'Kotor', country: 'Montenegro', region: ['europe'] },
  { city: 'Belgrade', country: 'Serbia', region: ['europe'] },
  { city: 'Bucharest', country: 'Romania', region: ['europe'] },
  { city: 'Sofia', country: 'Bulgaria', region: ['europe'] },
  { city: 'Tirana', country: 'Albania', region: ['europe'] },
  { city: 'Sarajevo', country: 'Bosnia', region: ['europe'] },

  // Turkey
  { city: 'Istanbul', country: 'Turkey', region: ['europe', 'middle_east'] },
  { city: 'Antalya', country: 'Turkey', region: ['europe', 'middle_east'] },
  { city: 'Bodrum', country: 'Turkey', region: ['europe', 'middle_east'] },
  { city: 'Cappadocia', country: 'Turkey', region: ['europe', 'middle_east'] },
  { city: 'Fethiye', country: 'Turkey', region: ['europe', 'middle_east'] },

  // Cyprus & Malta
  { city: 'Paphos', country: 'Cyprus', region: ['europe'] },
  { city: 'Larnaca', country: 'Cyprus', region: ['europe'] },
  { city: 'Malta', country: 'Malta', region: ['europe'] },

  // USA (expanded)
  { city: 'New York', country: 'USA', region: ['usa'] },
  { city: 'Los Angeles', country: 'USA', region: ['usa'] },
  { city: 'Miami', country: 'USA', region: ['usa'] },
  { city: 'Las Vegas', country: 'USA', region: ['usa'] },
  { city: 'San Francisco', country: 'USA', region: ['usa'] },
  { city: 'Chicago', country: 'USA', region: ['usa'] },
  { city: 'Orlando', country: 'USA', region: ['usa'] },
  { city: 'Nashville', country: 'USA', region: ['usa'] },
  { city: 'Austin', country: 'USA', region: ['usa'] },
  { city: 'New Orleans', country: 'USA', region: ['usa'] },
  { city: 'Boston', country: 'USA', region: ['usa'] },
  { city: 'Washington DC', country: 'USA', region: ['usa'] },
  { city: 'Seattle', country: 'USA', region: ['usa'] },
  { city: 'San Diego', country: 'USA', region: ['usa'] },
  { city: 'Denver', country: 'USA', region: ['usa'] },
  { city: 'Honolulu', country: 'USA', region: ['usa'] },
  { city: 'Portland', country: 'USA', region: ['usa'] },
  { city: 'Savannah', country: 'USA', region: ['usa'] },
  { city: 'Charleston', country: 'USA', region: ['usa'] },
  { city: 'Scottsdale', country: 'USA', region: ['usa'] },
  { city: 'Atlanta', country: 'USA', region: ['usa'] },
  { city: 'Dallas', country: 'USA', region: ['usa'] },
  { city: 'Houston', country: 'USA', region: ['usa'] },
  { city: 'Philadelphia', country: 'USA', region: ['usa'] },
  { city: 'Phoenix', country: 'USA', region: ['usa'] },
  { city: 'Minneapolis', country: 'USA', region: ['usa'] },
  { city: 'Detroit', country: 'USA', region: ['usa'] },
  { city: 'Salt Lake City', country: 'USA', region: ['usa'] },
  { city: 'Aspen', country: 'USA', region: ['usa'] },
  { city: 'Key West', country: 'USA', region: ['usa'] },
  { city: 'Maui', country: 'USA', region: ['usa'] },
  { city: 'Palm Springs', country: 'USA', region: ['usa'] },

  // Canada
  { city: 'Toronto', country: 'Canada', region: ['canada'] },
  { city: 'Vancouver', country: 'Canada', region: ['canada'] },
  { city: 'Montreal', country: 'Canada', region: ['canada'] },
  { city: 'Calgary', country: 'Canada', region: ['canada'] },
  { city: 'Ottawa', country: 'Canada', region: ['canada'] },
  { city: 'Quebec City', country: 'Canada', region: ['canada'] },
  { city: 'Banff', country: 'Canada', region: ['canada'] },
  { city: 'Whistler', country: 'Canada', region: ['canada'] },
  { city: 'Halifax', country: 'Canada', region: ['canada'] },
  { city: 'Victoria', country: 'Canada', region: ['canada'] },

  // Caribbean & Mexico (expanded)
  { city: 'Cancun', country: 'Mexico', region: ['caribbean'] },
  { city: 'Tulum', country: 'Mexico', region: ['caribbean'] },
  { city: 'Mexico City', country: 'Mexico', region: ['caribbean'] },
  { city: 'Playa del Carmen', country: 'Mexico', region: ['caribbean'] },
  { city: 'Cabo San Lucas', country: 'Mexico', region: ['caribbean'] },
  { city: 'Puerto Vallarta', country: 'Mexico', region: ['caribbean'] },
  { city: 'Jamaica', country: 'Jamaica', region: ['caribbean'] },
  { city: 'Barbados', country: 'Barbados', region: ['caribbean'] },
  { city: 'Bahamas', country: 'Bahamas', region: ['caribbean'] },
  { city: 'Punta Cana', country: 'Dominican Republic', region: ['caribbean'] },
  { city: 'St Lucia', country: 'St Lucia', region: ['caribbean'] },
  { city: 'Aruba', country: 'Aruba', region: ['caribbean'] },
  { city: 'Turks & Caicos', country: 'Turks & Caicos', region: ['caribbean'] },
  { city: 'Antigua', country: 'Antigua', region: ['caribbean'] },
  { city: 'Cuba', country: 'Cuba', region: ['caribbean'] },
  { city: 'Puerto Rico', country: 'Puerto Rico', region: ['caribbean'] },
  { city: 'St Barts', country: 'St Barts', region: ['caribbean'] },
  { city: 'Curacao', country: 'Curacao', region: ['caribbean'] },
  { city: 'Grenada', country: 'Grenada', region: ['caribbean'] },
  { city: 'Cayman Islands', country: 'Cayman Islands', region: ['caribbean'] },
  { city: 'Trinidad & Tobago', country: 'Trinidad & Tobago', region: ['caribbean'] },
  { city: 'St Kitts', country: 'St Kitts & Nevis', region: ['caribbean'] },

  // South America
  { city: 'Rio de Janeiro', country: 'Brazil', region: ['south_america'] },
  { city: 'Sao Paulo', country: 'Brazil', region: ['south_america'] },
  { city: 'Buenos Aires', country: 'Argentina', region: ['south_america'] },
  { city: 'Mendoza', country: 'Argentina', region: ['south_america'] },
  { city: 'Patagonia', country: 'Argentina', region: ['south_america'] },
  { city: 'Lima', country: 'Peru', region: ['south_america'] },
  { city: 'Cusco', country: 'Peru', region: ['south_america'] },
  { city: 'Bogota', country: 'Colombia', region: ['south_america'] },
  { city: 'Cartagena', country: 'Colombia', region: ['south_america'] },
  { city: 'Medellin', country: 'Colombia', region: ['south_america'] },
  { city: 'Santiago', country: 'Chile', region: ['south_america'] },
  { city: 'Quito', country: 'Ecuador', region: ['south_america'] },
  { city: 'Galapagos Islands', country: 'Ecuador', region: ['south_america'] },
  { city: 'Montevideo', country: 'Uruguay', region: ['south_america'] },

  // Asia (expanded)
  { city: 'Tokyo', country: 'Japan', region: ['asia'] },
  { city: 'Kyoto', country: 'Japan', region: ['asia'] },
  { city: 'Osaka', country: 'Japan', region: ['asia'] },
  { city: 'Bangkok', country: 'Thailand', region: ['asia'] },
  { city: 'Phuket', country: 'Thailand', region: ['asia'] },
  { city: 'Koh Samui', country: 'Thailand', region: ['asia'] },
  { city: 'Chiang Mai', country: 'Thailand', region: ['asia'] },
  { city: 'Krabi', country: 'Thailand', region: ['asia'] },
  { city: 'Bali', country: 'Indonesia', region: ['asia'] },
  { city: 'Jakarta', country: 'Indonesia', region: ['asia'] },
  { city: 'Singapore', country: 'Singapore', region: ['asia'] },
  { city: 'Hong Kong', country: 'Hong Kong', region: ['asia'] },
  { city: 'Seoul', country: 'South Korea', region: ['asia'] },
  { city: 'Busan', country: 'South Korea', region: ['asia'] },
  { city: 'Hanoi', country: 'Vietnam', region: ['asia'] },
  { city: 'Ho Chi Minh City', country: 'Vietnam', region: ['asia'] },
  { city: 'Da Nang', country: 'Vietnam', region: ['asia'] },
  { city: 'Kuala Lumpur', country: 'Malaysia', region: ['asia'] },
  { city: 'Langkawi', country: 'Malaysia', region: ['asia'] },
  { city: 'Penang', country: 'Malaysia', region: ['asia'] },
  { city: 'Manila', country: 'Philippines', region: ['asia'] },
  { city: 'Boracay', country: 'Philippines', region: ['asia'] },
  { city: 'Cebu', country: 'Philippines', region: ['asia'] },
  { city: 'Palawan', country: 'Philippines', region: ['asia'] },
  { city: 'Maldives', country: 'Maldives', region: ['asia'] },
  { city: 'Sri Lanka', country: 'Sri Lanka', region: ['asia'] },
  { city: 'Goa', country: 'India', region: ['asia'] },
  { city: 'Delhi', country: 'India', region: ['asia'] },
  { city: 'Mumbai', country: 'India', region: ['asia'] },
  { city: 'Jaipur', country: 'India', region: ['asia'] },
  { city: 'Bangalore', country: 'India', region: ['asia'] },
  { city: 'Kerala', country: 'India', region: ['asia'] },
  { city: 'Agra', country: 'India', region: ['asia'] },
  { city: 'Beijing', country: 'China', region: ['asia'] },
  { city: 'Shanghai', country: 'China', region: ['asia'] },
  { city: 'Taipei', country: 'Taiwan', region: ['asia'] },
  { city: 'Phnom Penh', country: 'Cambodia', region: ['asia'] },
  { city: 'Siem Reap', country: 'Cambodia', region: ['asia'] },
  { city: 'Luang Prabang', country: 'Laos', region: ['asia'] },
  { city: 'Kathmandu', country: 'Nepal', region: ['asia'] },
  { city: 'Yangon', country: 'Myanmar', region: ['asia'] },

  // Oceania
  { city: 'Sydney', country: 'Australia', region: ['oceania'] },
  { city: 'Melbourne', country: 'Australia', region: ['oceania'] },
  { city: 'Brisbane', country: 'Australia', region: ['oceania'] },
  { city: 'Perth', country: 'Australia', region: ['oceania'] },
  { city: 'Gold Coast', country: 'Australia', region: ['oceania'] },
  { city: 'Cairns', country: 'Australia', region: ['oceania'] },
  { city: 'Auckland', country: 'New Zealand', region: ['oceania'] },
  { city: 'Queenstown', country: 'New Zealand', region: ['oceania'] },
  { city: 'Wellington', country: 'New Zealand', region: ['oceania'] },
  { city: 'Fiji', country: 'Fiji', region: ['oceania'] },
  { city: 'Bora Bora', country: 'French Polynesia', region: ['oceania'] },

  // Middle East
  { city: 'Dubai', country: 'UAE', region: ['middle_east'] },
  { city: 'Abu Dhabi', country: 'UAE', region: ['middle_east'] },
  { city: 'Doha', country: 'Qatar', region: ['middle_east'] },
  { city: 'Riyadh', country: 'Saudi Arabia', region: ['middle_east'] },
  { city: 'Jeddah', country: 'Saudi Arabia', region: ['middle_east'] },
  { city: 'Muscat', country: 'Oman', region: ['middle_east'] },
  { city: 'Bahrain', country: 'Bahrain', region: ['middle_east'] },
  { city: 'Tel Aviv', country: 'Israel', region: ['middle_east'] },
  { city: 'Jerusalem', country: 'Israel', region: ['middle_east'] },
  { city: 'Amman', country: 'Jordan', region: ['middle_east'] },
  { city: 'Petra', country: 'Jordan', region: ['middle_east'] },

  // Africa
  { city: 'Cape Town', country: 'South Africa', region: ['africa'] },
  { city: 'Johannesburg', country: 'South Africa', region: ['africa'] },
  { city: 'Marrakech', country: 'Morocco', region: ['africa'] },
  { city: 'Fez', country: 'Morocco', region: ['africa'] },
  { city: 'Casablanca', country: 'Morocco', region: ['africa'] },
  { city: 'Zanzibar', country: 'Tanzania', region: ['africa'] },
  { city: 'Dar es Salaam', country: 'Tanzania', region: ['africa'] },
  { city: 'Nairobi', country: 'Kenya', region: ['africa'] },
  { city: 'Mombasa', country: 'Kenya', region: ['africa'] },
  { city: 'Cairo', country: 'Egypt', region: ['africa'] },
  { city: 'Sharm El Sheikh', country: 'Egypt', region: ['africa'] },
  { city: 'Hurghada', country: 'Egypt', region: ['africa'] },
  { city: 'Accra', country: 'Ghana', region: ['africa'] },
  { city: 'Lagos', country: 'Nigeria', region: ['africa'] },
  { city: 'Mauritius', country: 'Mauritius', region: ['africa'] },
  { city: 'Seychelles', country: 'Seychelles', region: ['africa'] },
  { city: 'Victoria Falls', country: 'Zimbabwe', region: ['africa'] },
  { city: 'Windhoek', country: 'Namibia', region: ['africa'] },
  { city: 'Kigali', country: 'Rwanda', region: ['africa'] },
  { city: 'Addis Ababa', country: 'Ethiopia', region: ['africa'] },
  { city: 'Tunis', country: 'Tunisia', region: ['africa'] },
]

export const regionLabels: Record<Region, string> = {
  anywhere: 'Anywhere in the world',
  europe: 'Europe',
  uk: 'UK only',
  usa: 'USA',
  asia: 'Asia & Pacific',
  caribbean: 'Caribbean & Mexico',
  middle_east: 'Middle East',
  oceania: 'Australia & Pacific',
  south_america: 'South America',
  canada: 'Canada',
  africa: 'Africa',
}

export const regionIcons: Record<Region, string> = {
  anywhere: 'GL',
  europe: 'EU',
  uk: 'UK',
  usa: 'US',
  asia: 'AS',
  caribbean: 'CB',
  middle_east: 'ME',
  oceania: 'OC',
  south_america: 'SA',
  canada: 'CA',
  africa: 'AF',
}

export function getFilteredDestinations(scope: Region): Destination[] {
  if (scope === 'anywhere') return destinations
  return destinations.filter((d) => d.region.includes(scope))
}

export function searchDestinations(query: string, scope: Region): Destination[] {
  const filtered = getFilteredDestinations(scope)
  if (!query.trim()) return filtered.slice(0, 8) // show 8 suggestions by default
  const q = query.toLowerCase()
  return filtered
    .filter(
      (d) =>
        d.city.toLowerCase().includes(q) ||
        d.country.toLowerCase().includes(q)
    )
    .slice(0, 8)
}
